"use client";
import { Box, Flex, Text } from "@chakra-ui/react";
import { CheckCircleIcon, SparkleIcon } from "@phosphor-icons/react";
import { Tooltip } from "./ui/tooltip";

const AI_DISCLAIMER =
  "This visualization includes AI-generated charts and data summaries. AI models may produce incomplete or incorrect information. Please verify all outputs before using them in your work.";

// Curated insights come from a verified, direct data query — not AI — so the
// hover note reassures rather than disclaims.
const CURATED_NOTE =
  "This analysis was produced from a verified, direct data query rather than generated by AI, so its charts and figures come straight from the source data.";

function CaptionTooltip({ heading, body }: { heading: string; body: string }) {
  return (
    <Box display="flex" flexDirection="column" gap="2px" maxW="296px">
      <Text
        fontFamily="body"
        fontSize="12px"
        lineHeight="150%"
        fontWeight="medium"
        color="#FFFFFF"
      >
        {heading}
      </Text>
      <Text
        fontFamily="body"
        fontSize="12px"
        lineHeight="150%"
        fontWeight="normal"
        color="#B2B6BD"
      >
        {body}
      </Text>
    </Box>
  );
}

/**
 * Caption shown at the top of an insight card in the workspace and the analysis
 * panel's detail view. Both variants carry a "Learn more" link whose hover note
 * differs; `showLearnMore={false}` drops the link for the compact panel-card
 * badge (which reuses only the icon + label).
 * curated → green check-circle + "CURATED" (verified, direct-query flow)
 * default → gray sparkle + "AI-ASSISTED" (AI-generated, carries a disclaimer)
 */
export default function InsightCaption({
  curated,
  showLearnMore = true,
}: {
  curated?: boolean;
  showLearnMore?: boolean;
}) {
  return (
    <Flex align="center" gap="4px" h="16px">
      {curated ? (
        <CheckCircleIcon size={12} color="#009E77" />
      ) : (
        <SparkleIcon size={12} weight="thin" color="#737C94" />
      )}
      <Text
        fontSize="10px"
        fontFamily="mono"
        fontWeight="normal"
        lineHeight="16px"
        letterSpacing="0.03em"
        color={curated ? "#656E7B" : "#737C94"}
        whiteSpace="nowrap"
      >
        {curated ? "CURATED" : "AI-ASSISTED"}
        {showLearnMore && (
          <>
            {" · "}
            <Tooltip
              variant="dark"
              content={
                curated ? (
                  <CaptionTooltip heading="CURATED" body={CURATED_NOTE} />
                ) : (
                  <CaptionTooltip heading="AI-ASSISTED" body={AI_DISCLAIMER} />
                )
              }
              showArrow
              positioning={{ placement: "bottom" }}
              openDelay={100}
              closeDelay={100}
            >
              <Box
                as="span"
                color="#0049AA"
                textDecoration="underline"
                cursor="help"
                tabIndex={0}
                aria-label={
                  curated
                    ? "Learn more about curated analysis"
                    : "Learn more about AI-assisted analysis"
                }
              >
                Learn more
              </Box>
            </Tooltip>
          </>
        )}
      </Text>
    </Flex>
  );
}
