"use client";
import { useState, useEffect } from "react";
import { Box, Flex, Text, IconButton, chakra } from "@chakra-ui/react";
import { SparkleIcon, WarningIcon, XIcon } from "@phosphor-icons/react";
const Sparkle = chakra(SparkleIcon);
const Warning = chakra(WarningIcon);

const COOKIE_KEY = "ai_disclaimer_dismissed_X";

function getCookie(name: string): string | undefined {
  if (typeof document === "undefined") return undefined;
  return document.cookie
    .split("; ")
    .find((row) => row.startsWith(`${name}=`))
    ?.split("=")[1];
}

function setCookie(name: string, value: string, days = 365) {
  const expires = new Date(Date.now() + days * 864e5).toUTCString();
  document.cookie = `${name}=${value}; expires=${expires}; path=/; SameSite=Lax`;
}

interface VisualizationDisclaimerProps {
  variant?: "inline" | "overlay";
}

export default function VisualizationDisclaimer({
  variant = "inline",
}: VisualizationDisclaimerProps) {
  const [dismissed, setDismissed] = useState(false);

  useEffect(() => {
    setDismissed(getCookie(COOKIE_KEY) === "1");
  }, []);

  const handleDismiss = () => {
    setCookie(COOKIE_KEY, "1");
    setDismissed(true);
  };

  if (dismissed) {
    return (
      <Flex align="center" gap="1.5">
        <Warning color="fg.subtle" boxSize="2.5" flexShrink={0} />
        <Text fontSize="xs" color="fg.subtle">
          Generated by AI — verify before use.
        </Text>
      </Flex>
    );
  }

  const message =
    "This visualization includes AI-generated charts and data summaries. AI models may produce incomplete or incorrect information. Please verify all outputs before using them in your work.";

  const content = (
    <Flex align="flex-start" gap="2">
      <Sparkle color="secondary.500" weight="fill" mt="0.5" flexShrink={0} />
      <Text fontSize="xs" color="fg.muted" flex="1">
        {message}
      </Text>
      <IconButton
        aria-label="Dismiss"
        size="xs"
        variant="ghost"
        color="fg.subtle"
        minW="auto"
        h="auto"
        p="0.5"
        onClick={handleDismiss}
        _hover={{ color: "fg" }}
      >
        <XIcon size={12} />
      </IconButton>
    </Flex>
  );

  if (variant === "overlay") {
    return (
      <Box
        bg="bg"
        color="fg"
        borderRadius="md"
        borderWidth="1px"
        borderColor="border.emphasized"
        p="2.5"
        maxW={{ base: "calc(100% - 16px)", md: "640px" }}
      >
        {content}
      </Box>
    );
  }

  return (
    <Box
      bg="bg"
      color="fg"
      borderRadius="md"
      borderWidth="1px"
      borderColor="border.emphasized"
      p="2.5"
    >
      {content}
    </Box>
  );
}


